
services:
  codex-frontend:
    image: codexstorage/codex-frontend:latest
    ports:
      - 3000:80
    environment:
     - codex_url=http://my-codex-node:8080
    depends_on:
      - my-codex-node

  my-codex-node:
    image: codexstorage/nim-codex:latest-dist-tests
    ports:
      - 8080:8080/tcp # API port
      - 8090:8090/udp # Discovery port
      - 8070:8070/tcp # Listen port
    environment:
      - CODEX_LOG_LEVEL=Trace
      - CODEX_API_PORT=8080
      - CODEX_API_BINDADDR=0.0.0.0
      - CODEX_LISTEN_ADDRS=/ip4/0.0.0.0/tcp/8070
      - CODEX_DISC_PORT=8090
      - CODEX_BOOTSTRAP_NODE=spr:CiUIAhIhAlrt4nrtZA6BtsyuUS2lJoZQQaRjItOCvdbNBWAwjpXNEgIDARo8CicAJQgCEiECWu3ieu1kDoG2zK5RLaUmhlBBpGMi04K91s0FYDCOlc0QpunsqgYaCwoJBJ_f5lWRAnVOKkcwRQIhANP3hAuwJpazzbj6kLlB2QNfAMeL6mbaRDBigZHVzJvdAiBuyNcpvulJ7O8D4enYhASY05UfxBLUl0VMHJptwWv6KQ
      - NAT_PUBLIC_IP_AUTO=https://ip.codex.storage
      - NAT_IP_AUTO=false

      - CODEX_ETH_PROVIDER=ws://my-geth:8083
      - CODEX_PERSISTENCE=true
      - CODEX_VALIDATOR=false
      - CODEX_MARKETPLACE_ADDRESS=0x92F09Aa59DcCb892a9f5406DDd9c0b98f02EA57e

      - PRIV_KEY=<YOUR-KEY-HERE>
    volumes:
      - ./datadir:/datadir
    depends_on:
      - my-geth

  my-geth:
    image: codexstorage/dist-tests-geth:latest
    environment:
      - ENABLE_MINER=1
      - UNLOCK_START_INDEX=0
      - UNLOCK_NUMBER=1
      - GETH_ARGS=--http.addr 0.0.0.0 --http.port 30000 --port 8081 --discovery.port 8080 --ipcdisable --syncmode full --authrpc.port 8082 --ws --ws.addr 0.0.0.0 --ws.port 8083

  # Not needed when geth node is bootstrapped.
  # apply-contracts:
  #   image: codexstorage/codex-contracts-eth:sha-1854dfb-dist-tests
  #   environment:
  #     - DISTTEST_NETWORK_URL=http://my-geth:30000
  #     - HARDHAT_NETWORK=codexdisttestnetwork
  #     - KEEP_ALIVE=1
